### ISSUE TITLE
get only black screen

### ISSUE THREAD

**Issue by JimFlasch** [Lemon-King/HXDD#12] opened 2024-09-01 21:21 UTC
This mod has an annoying bug. I can only start a new game via the map console command (map ExMy or map mapxx). I cannot start a new game via the menu. After making my choices in the start menu and clicking start, all I get is a black screen. This happens regardless of which class, episode or anything else I choose. I use Windows 10, built hexdd.ipk3 with the latest version of the app (0.8.3) and have the latest GZDoom 4.13 preview installed.

**Comment by Lemon-King** [comment] 2024-09-02 02:57
Do you have the Vulkan renderer enabled in GZDoom?

**Comment by JimFlasch** [comment] 2024-09-02 02:58
No. This needs that?

**Comment by Lemon-King** [comment] 2024-09-02 02:58
No. But looking on the discord its one of the causes.

Do you know your video card and how much vram you have?

**Comment by JimFlasch** [comment] 2024-09-02 03:14
Actually, it wasn't Vulkan being disabled. I have the AIMP music player installed on my computer and while doing some testing just now discovered that the issue only occurs when AIMP is in mini player mode - the player shows over the game window, which goes all black, when I click start if that's the case. If AIMP is in default mode, this mod works fine. This is the only GZDoom mod I've encountered with this behavior.

**Comment by Lemon-King** [comment] 2024-09-02 03:17
Glad its resolved! I'll keep in mind that background programs can influence GZDoom when it comes to troubleshooting.

**Comment by Lemon-King** [comment] 2024-09-02 03:17
Closing this as its resolved.

**Closed by Lemon-King** 2024-09-02 03:17 UTC
